# Outline

- PyTorch
- What are tensors
- Initialising, slicing, reshaing tensors
- Numpy and PyTorch interfacing
- GPU support on PyTorch + enabling GPUs on Colab
- Speed comparision - NumPy vs PyTorch vs PyTorch GPU
- Autograd concept and application
- Writting a basic learning loop using autograd
- Exercise

In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import tqdm

# Initilising Tensors

In [ ]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.9072, 0.8992],
        [0.1805, 0.2700],
        [0.0277, 0.9003]])


In [ ]:
x = torch.empty(3, 2)
print(x)

y = torch.zeros_like(x)
print(y)

tensor([[-2.7373e-25,  3.0802e-41],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
x = torch.linspace(0, 1, steps=25)
print(x)

tensor([0.0000, 0.0417, 0.0833, 0.1250, 0.1667, 0.2083, 0.2500, 0.2917, 0.3333,
        0.3750, 0.4167, 0.4583, 0.5000, 0.5417, 0.5833, 0.6250, 0.6667, 0.7083,
        0.7500, 0.7917, 0.8333, 0.8750, 0.9167, 0.9583, 1.0000])


In [ ]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]
                ])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


# Slicing

In [ ]:
x[0:2,:]

tensor([[1, 2],
        [3, 4]])

In [ ]:
y = x[1, 1]
print(y)
print(y.item())

tensor(4)
4


# Reshaping Tensors

In [ ]:
print(x)
x.view(2,3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.view(6, -1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
x.T

tensor([[1, 3, 5],
        [2, 4, 6]])

# Simple Tensor Operations

In [ ]:
x = torch.ones(3, 2)
y = torch.ones(3, 2)
print(x + y)
print(x - y)
print(x * y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
z = y.add(x)
print(z)
print(y)
print("---------------")
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
---------------
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# NumPy <> PyTorch

In [ ]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.random.randn(3, 2)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([[ 0.4432, -1.2318],
        [-1.7743,  0.4947],
        [ 0.8362, -0.8624]], dtype=torch.float64)


In [ ]:
np.add(a, 1, out=a)
print(a)
print(a_pt)

[[ 1.44321241 -0.23182357]
 [-0.77434426  1.49474445]
 [ 1.8362174   0.13756052]]
tensor([[ 1.4432, -0.2318],
        [-0.7743,  1.4947],
        [ 1.8362,  0.1376]], dtype=torch.float64)


In [ ]:
%%time
for i in range(100):
    a = np.random.randn(100, 100)
    b = np.random.randn(100, 100)
    c = np.matmul(a, b)

CPU times: user 164 ms, sys: 104 ms, total: 268 ms
Wall time: 141 ms


In [ ]:
%%time
for i in range(100):
    a = torch.randn(100, 100)
    b = torch.randn(100, 100)
    c = torch.matmul(a, b)

CPU times: user 31.3 ms, sys: 0 ns, total: 31.3 ms
Wall time: 32.1 ms


In [ ]:
%%time
for i in range(10):
    a = np.random.randn(10000, 10000)
    b = np.random.randn(10000, 10000)
    c = a + b

CPU times: user 1min 27s, sys: 1.2 s, total: 1min 28s
Wall time: 1min 28s


In [ ]:
%%time
for i in range(10):
    a = torch.randn(10000, 10000)
    b = torch.randn(10000, 10000)
    c = a + b

CPU times: user 22.7 s, sys: 88.9 ms, total: 22.8 s
Wall time: 22.8 s


# CUDA Support 

In [ ]:
print(torch.cuda.device_count())

1


In [12]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name())

Tesla P100-PCIE-16GB


In [13]:
cuda0 = torch.device('cuda:0')

In [ ]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(a, b, c)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0') tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0') tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [ ]:
%%time
for i in range(10):
    a = np.random.randn(10000, 10000)
    b = np.random.randn(10000, 10000)
    np.add(a, b)

CPU times: user 1min 15s, sys: 68.2 ms, total: 1min 15s
Wall time: 1min 15s


In [ ]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000])
    b = torch.randn([10000, 10000])
    b.add_(a)

CPU times: user 18.2 s, sys: 20.8 ms, total: 18.3 s
Wall time: 18.2 s


In [ ]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000], device=cuda0)
    b = torch.randn([10000, 10000], device=cuda0)
    b.add_(a)

CPU times: user 2.46 ms, sys: 5 µs, total: 2.47 ms
Wall time: 1.83 ms


In [ ]:
%%time
for i in range(10):
    a = np.random.randn(10000, 10000)
    b = np.random.randn(10000, 10000)
    np.matmul(a, b)

CPU times: user 12min 33s, sys: 5.76 s, total: 12min 39s
Wall time: 7min 1s


In [ ]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000])
    b = torch.randn([10000, 10000])
    torch.matmul(b, a)

CPU times: user 2min 50s, sys: 178 ms, total: 2min 50s
Wall time: 2min 49s


In [ ]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000], device=cuda0)
    b = torch.randn([10000, 10000], device=cuda0)
    torch.matmul(b, a)

CPU times: user 3.22 ms, sys: 995 µs, total: 4.22 ms
Wall time: 12.1 ms


# Autograd

In [2]:
x = torch.ones([3, 2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [4]:
z = y * y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [5]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [6]:
t.backward()

In [7]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [8]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1 / (1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [9]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1 / (1 + torch.exp(-y))
a = torch.ones([3, 2], requires_grad=True)
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


# autograd & Loss function

In [19]:
x = torch.randn([20, 1], requires_grad=True)
y = 3*x - 2

In [20]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
y_hat = w*x + b

loss = torch.sum((y_hat - y) ** 2)

In [21]:
print(loss)

tensor(266.1360, grad_fn=<SumBackward0>)


In [22]:
loss.backward()

In [23]:
print(w.grad, b.grad)

tensor([-85.6028]) tensor([120.3555])


# Loop for Loss 

In [4]:
learning_rate = 0.01
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
print(w.item(), b.item())

for i in range(10):
    x = torch.randn([20, 1])
    y = 3*x - 2

    y_hat = w*x + b
    loss = torch.sum((y_hat - y)**2)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * w.grad
    
        w.grad.zero_()
        b.grad.zero_()
    print(w.item(), b.item())


1.0 1.0
1.7100043296813965 1.7100043296813965
2.2627620697021484 2.2627620697021484
2.463947296142578 2.463947296142578
2.5571177005767822 2.5571177005767822
2.754178285598755 2.754178285598755
3.234315872192383 3.234315872192383
2.7839300632476807 2.7839300632476807
2.835768461227417 2.835768461227417
3.3014588356018066 3.3014588356018066
3.445589303970337 3.445589303970337


In [20]:
%%time
learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.randn([N], requires_grad=True)
b = torch.ones([1], requires_grad=True)

for i in range(epochs):

    x = torch.randn([N])
    y = torch.dot(3 * torch.ones([N]), x) - 2

    y_hat = torch.dot(w, x) + b
    loss = torch.sum((y_hat - y)**2)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()

    # print(torch.mean(w).item(), b.item())

CPU times: user 29.9 s, sys: 273 ms, total: 30.1 s
Wall time: 30 s


In [22]:
%%time
learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.randn([N], requires_grad=True, device=cuda0)
b = torch.ones([1], requires_grad=True, device=cuda0)

for i in range(epochs):

    x = torch.randn([N], device=cuda0)
    y = torch.dot(3 * torch.ones([N], device=cuda0), x) - 2

    y_hat = torch.dot(w, x) + b
    loss = torch.sum((y_hat - y)**2)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()

    # print(torch.mean(w).item(), b.item())

CPU times: user 165 ms, sys: 92.6 ms, total: 257 ms
Wall time: 261 ms
